### ISSUE TITLE
Crashed app

### ISSUE THREAD

**Issue by abtris** [apiaryio/slack-here-bot#2]
```
2015-06-02T10:02:04.128736+00:00 app[worker.1]: /app/index.js:58
2015-06-02T10:02:04.128741+00:00 app[worker.1]:         var match = message.text.match(/@here/);
2015-06-02T10:02:04.128743+00:00 app[worker.1]:                                 ^
2015-06-02T10:02:04.128744+00:00 app[worker.1]: TypeError: Cannot read property 'match' of undefined
2015-06-02T10:02:04.128746+00:00 app[worker.1]:     at Client.<anonymous> (/app/index.js:58:33)
2015-06-02T10:02:04.128747+00:00 app[worker.1]:     at Client.emit (events.js:107:17)
2015-06-02T10:02:04.128749+00:00 app[worker.1]:     at Client.onMessage (/app/node_modules/slack-client/src/client.js:477:14)
2015-06-02T10:02:04.128753+00:00 app[worker.1]:     at WebSocket.<anonymous> (/app/node_modules/slack-client/src/client.js:140:24)
2015-06-02T10:02:04.128754+00:00 app[worker.1]:     at WebSocket.emit (events.js:110:17)
2015-06-02T10:02:04.128756+00:00 app[worker.1]:     at Receiver.self._receiver.ontext (/app/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:697:10)
2015-06-02T10:02:04.128758+00:00 app[worker.1]:     at Receiver.opcodes.1.finish (/app/node_modules/slack-client/node_modules/ws/lib/Receiver.js:397:14)
2015-06-02T10:02:04.128759+00:00 app[worker.1]:     at Receiver.expectHandler (/app/node_modules/slack-client/node_modules/ws/lib/Receiver.js:384:31)
2015-06-02T10:02:04.128761+00:00 app[worker.1]:     at Receiver.add (/app/node_modules/slack-client/node_modules/ws/lib/Receiver.js:93:24)
2015-06-02T10:02:04.128762+00:00 app[worker.1]:     at TLSSocket.firstHandler (/app/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
2015-06-02T10:02:04.821958+00:00 heroku[worker.1]: Process exited with status 1
2015-06-02T10:02:04.841650+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by abtris** [comment]
Fix in #1
