### ISSUE TITLE
Crashed app

### ISSUE THREAD

**Issue by abtris** [apiaryio/slack-here-bot#9]
```
/app/src/index.js:50
2015-06-10T12:43:19.297418+00:00 app[worker.1]:           .filter(function(u) { return u.id != user.id; })
2015-06-10T12:43:19.297422+00:00 app[worker.1]: TypeError: Cannot read property 'id' of undefined
2015-06-10T12:43:19.297423+00:00 app[worker.1]:     at /app/src/index.js:50:52
2015-06-10T12:43:19.297425+00:00 app[worker.1]:     at Array.filter (native)
2015-06-10T12:43:19.297426+00:00 app[worker.1]:     at Client.<anonymous> (/app/src/index.js:50:12)
```

**Comment by abtris** [comment]
Missing user.id is problem.
